pipeline {
    agent any

    environment {
        IMAGE_NAME = "jrodga1604/sparta-app"
        EC2_HOST = "54.229.62.115"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('app') {
                    sh """
                        docker buildx create --use --name multi-builder || true
                        docker buildx build \
                          --platform linux/amd64 \
                          -t ${IMAGE_NAME}:${BUILD_NUMBER} \
                          -t ${IMAGE_NAME}:latest \
                          --push .
                    """
                }
            }
        }

        stage('Deploy to Kubernetes') {
            when {
                branch 'main'
            }
            steps {
                sshagent(['ec2-ssh-key']) {
                    sh """
                    ssh -o StrictHostKeyChecking=no ubuntu@${EC2_HOST} '
                        sudo kubectl -n sparta set image deployment/sparta-app \
                        sparta-app=${IMAGE_NAME}:${BUILD_NUMBER}
                    '
                    """
                }
            }
        }
    }
}








